AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Slack Commands

Parameters:
  SigningSecret:
    Description: Slack signing secret
    Type: String
    Default: undefined
    NoEcho: true

  SlackBotToken:
    Description: Slack bot token
    Type: String
    Default: undefined
    NoEcho: true

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  SlackCommands:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../src
      Handler: main.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SigningSecret
          SLACK_BOT_TOKEN: !Ref SlackBotToken
      Architectures:
        - x86_64
      Events:
        Commands:
          Type: Api
          Properties:
            Path: /slack/events
            Method: post

Outputs:
  Api:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/slack/events/
