AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Slack Commands

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  SlackCommands:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        Commands:
          Type: Api
          Properties:
            Path: /commands
            Method: get

Outputs:
  Api:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/commands/
